### ISSUE TITLE
Input Decorators do not work on base classes.

### ISSUE THREAD

**Issue by jhuntoo** [WoltersKluwerPL/ng2-spin-kit#12]
The curent implementation uses the Input() decorators on the BaseSpinner class. These are not inherited by the the individual spinner components, and as such, you can't change the visibility of the spinners.

See https://github.com/angular/angular/issues/7968

**Comment by mrzepinski** [comment]
@jhuntoo Please try `0.4.0` version.

**Comment by mrzepinski** [comment]
@jhuntoo Ping ;)
