### ISSUE TITLE
Angular2 rc4 compatibility

### ISSUE THREAD

**Issue by kamikaze** [WoltersKluwerPL/ng2-spin-kit#13]
Please make it compatible with angular2 rc4 (at least update requirements)

**Comment by kamikaze** [comment]
https://github.com/WoltersKluwerPL/ng2-spin-kit/pull/14

**Comment by kamikaze** [comment]
Have no idea why it become closed by me o_O

**Comment by kamikaze** [comment]
Here is a PR: https://github.com/WoltersKluwerPL/ng2-spin-kit/pull/14

**Comment by mrzepinski** [comment]
@kamikaze Thanks for you PR. It's not easy to follow AJS changes.. ;)

I looked at your code and I think it will work only for SystemJS users. Webpack and others will be broken by current convection.

**Comment by kamikaze** [comment]
I have no eхerience with others :/ as it was before PR - it was not even
compiling for me.
14 июля 2016 г. 8:03 пользователь "Maciej Rzepiński" <
notifications@github.com> написал:

**Comment by mrzepinski** [comment]
@kamikaze I'll try to upgrade to RC4 later, but without modyfing convenction to support many module loaders ;)
