### ISSUE TITLE
...rotating-plane.html 404 (Not Found)

### ISSUE THREAD

**Issue by stefanstelzer** [WoltersKluwerPL/ng2-spin-kit#18]
Hey folks,

I implemented your spinner as guided but facing a 404 GET Error like this ...http://localhost:3000/rotating-plane.html 404 (Not Found)

Can anybody help me?

**Comment by mrzepinski** [comment]
@stefanstelzer Do you use any module loader? Webpack, JSPM or any other? I think that it could be related to your configuration.

You should look at: https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html

**Comment by bencameron00** [comment]
I am having this same issue, how did you solve it Stefan. I am using webpack.

**Comment by mrzepinski** [comment]
@stefanstelzer @bencameron00 Check `1.0.0` version :)

**Comment by stefanstelzer** [comment]
@mrzepinski 

Thanks for your reply, have been in holidays, sorry for my late response.

Will install 1.0.0 and will give you feedback this afternoon.

**Comment by mrzepinski** [comment]
@stefanstelzer How did you go?

**Comment by bencameron00** [comment]
I decided to write my own component in the end.

Thanks for the help though.

**Comment by jrgleason** [comment]
@bencameron00 Close then?

**Comment by bencameron00** [comment]
Yes I think so. Thanks.
