### ISSUE TITLE
error reflect-metadata needed

### ISSUE THREAD

**Issue by born2net** [WoltersKluwerPL/ng2-spin-kit#2]
getting

```
Error: reflect-metadata shim is required when using class decorators
	Evaluating http://localhost:8080/jspm_packages/npm/angular2@2.0.0-beta.14/src/core/util/decorators.js
	Evaluating http://localhost:8080/jspm_packages/npm/angular2@2.0.0-beta.14/src/core/di/decorators.js
	Evaluating http://localhost:8080/jspm_packages/npm/angular2@2.0.0-beta
```

which is odd since I have no issues with any other lib
```
import "reflect-metadata";
```

any ideas?

regards

**Comment by mrzepinski** [comment]
@born2net `reflect-metadata` comes from https://angular.io/docs/ts/latest/quickstart.html

Could you provide me more informations how do you use ng2-spin-kit?

**Comment by born2net** [comment]
well I am using it in a fairly large project, but basically its powered by jspm...
I guess I will play with it some more, but just was at odds as to why it errored 
will report back

**Comment by mrzepinski** [comment]
@born2net New version `0.0.2` is available. I updated some dependencies.

**Comment by born2net** [comment]
ok will check today

Regards,

Checkout the Ultimate Angular 2 Boorstrap App: @ http://ng2.javascriptninja.io
Source@ https://github.com/born2net/ng2Boilerplate

**Comment by mrzepinski** [comment]
@born2net Did you handle this?

**Comment by mrzepinski** [comment]
@born2net Ping ;)
