### ISSUE TITLE
auto generate .js

### ISSUE THREAD

**Issue by vislesh** [WoltersKluwerPL/ng2-spin-kit#20]
if i have to use this for my project , where do i have to execute `npm run tsc` ? meaning how to auto generate .js files during build ?

**Comment by mrzepinski** [comment]
@vislesh Which module bundler do you use? `npm run tsc` is required when do U want to import TS files in your code. Generally this is not required to use.

**Comment by vislesh** [comment]
@mrzepinski , im using systemjs.

**Comment by mrzepinski** [comment]
@vislesh Do you use any of Webpack, JSPM, smth else? Could you create some snippet of code to show how do you want to use this lib?

**Comment by vislesh** [comment]
in package.json :
"dependencies": {
"ng2-spin-kit": "^1.0.1"
}

in X.components.ts --
import {WaveComponent} from 'ng2-spin-kit/app/spinner/wave'
@Component({
  templateUrl: 'app/X.component.html',
  directives: [WaveComponent]
})

in X.component.html --
<sk-wave [isRunning]="loading" [delay]=100></sk-wave>

then i have Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/ng2-spin-kit/app/spinner/wave.js

**Comment by mrzepinski** [comment]
@vislesh And what should be the correct path in your project?

`http://localhost:5555/node_modules/ng2-spin-kit/app/spinner/wave.js` looks as it should be smth like this.

Can you provide your `systemjs` configuration here?

**Comment by vislesh** [comment]
![fs](https://cloud.githubusercontent.com/assets/10396738/18667829/c080d460-7f4f-11e6-9fd8-f1201aec2af3.JPG)

this is my filestructure , above mentioned path is correct . but there is no .js file over there. can you point to which file snippet would you like to see.

**Comment by mrzepinski** [comment]
@vislesh Your `SystemJS` configuration try to load JS files by default. You have to override it for ng2-spin-kit to load TS files by setting `defaultExtentsion` to `js` for SK - look at: https://github.com/WoltersKluwerPL/ng2-spin-kit/blob/master/systemjs.config.js

I've created `1.0.2` version with JS files which you can use in your project/

**Comment by vislesh** [comment]
@mrzepinski  , Thanks a lot. now its working.
