### ISSUE TITLE
Upgrade to ~2.0.1

### ISSUE THREAD

**Issue by jrgleason** [WoltersKluwerPL/ng2-spin-kit#21]
Currently this project is on the rc lets upgrade it to the release. For example in my app when I try to use this I get...

    Uncaught Error: No Directive annotation found on ChasingDotsComponent

**Comment by mrzepinski** [comment]
@jrgleason `1.1.0` is available ;) Please update.

**Comment by jrgleason** [comment]
Oops missed this and already issued a pull request, I will cancel it until I confirm the new version works

**Comment by jrgleason** [comment]
I also confirmed NPM was pulling the proper version when npm install --save
