### ISSUE TITLE
Add "main" js file to package.json

### ISSUE THREAD

**Issue by atais** [WoltersKluwerPL/ng2-spin-kit#26]
Please add compiled javascript file as well as "main" js key in the `package.json` file. 

It would allow for an easier import of the library in projects, simply by name:

```
import {FadingCircleComponent} from 'ng2-spin-kit';
```

instead of:
```
import {FadingCircleComponent} from 'ng2-spin-kit/app/spinners';
```

**Comment by mrzepinski** [comment]
@atais Could you create your own PR with that change? I'll merge that.
