### ISSUE TITLE
unable to include using angular-cli !!

### ISSUE THREAD

**Issue by olakara** [WoltersKluwerPL/ng2-spin-kit#3]
Hi,
 I am trying to get the spin kit working for a application built using angular-cli. I keep getting this error when running my application:

> Failed to load resource: the server responded with a status of 404 (Not Found)
> zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/angular2/core
> 	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
> 	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
> 	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
> 	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
> 	Error loading http://localhost:4200/angular2/core as "angular2/core" from http://localhost:4200/vendor/ng2-spin-kit/app/spinner/rotating-plane/rotating-plane.component.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/angular2/core(…)consoleError @ zone.js:461
> zone.js:463 Error: Uncaught (in promise): Error: Error: XHR error (404 Not Found) loading http://localhost:4200/angular2/core(…)consoleError @ zone.js:463
> http://localhost:4200/angular2/core Failed to load resource: the server responded with a status of 404 (Not Found)

Here is my angular-cli-build.js:
`module.exports = function(defaults) {

  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/*.js',
      'es6-shim/es6-shim.js',
      'reflect-metadata/*.js',
      'rxjs/**/*.js',
      '@angular/**/*.js',
      'ng2-spin-kit/app/**/*.js'
    ]
  });
};`

and my system-config.js

`/** Map relative paths to URLs. */
var map = {
    'ng2-spin-kit/app': 'vendor/ng2-spin-kit/app'
};
/** User packages configuration. */
var packages = {
    'ng2-spin-kit/app': {
        defaultExtension: 'js',
    }
};`

The spin-kit components seems to be looking for angular2/core again..

**Comment by mrzepinski** [comment]
@olakara `ng2-spin-kit` is based on latest beta (2.0.0-beta.15) release of AJS 2.x
I'll try to upgrade this to RC release and I'll let you know.

**Comment by mrzepinski** [comment]
@olakara Try `0.1.0` version :)

**Comment by mrzepinski** [comment]
@olakara Some improvement?

**Comment by olakara** [comment]
Unfortunately, I have been busy with other things.. will be able to get some free time today evening.. and will try then :)

**Comment by mrzepinski** [comment]
@olakara Ping ;)
