### ISSUE TITLE
base-spinner.ts: Type 'Timer' is not assignable to type 'number'.

### ISSUE THREAD

**Issue by ncfx** [WoltersKluwerPL/ng2-spin-kit#4]
ng2-spin-kit/app/spinner/base-spinner.ts:21:5 
    Type 'Timer' is not assignable to type 'number'.

**Comment by mrzepinski** [comment]
@ncfx setTimeout function is declared as:

```
declare function setTimeout(handler: any, timeout?: any, ...args: any[]): number;
```

So it should be a number.

**Comment by ncfx** [comment]
I'm using the nodeJS typing and it declares the setTimeout return value as a Timer object:
`declare function setTimeout(callback: (...args: any[]) => void, ms: number, ...args: any[]): NodeJS.Timer;`

Any chance you can change the timeout type to any?

**Comment by mrzepinski** [comment]
Sure. New version is available.

https://github.com/WoltersKluwerPL/ng2-spin-kit/releases/tag/0.1.1
