### ISSUE TITLE
hardcoded templateUrl paths === broken

### ISSUE THREAD

**Issue by ncfx** [WoltersKluwerPL/ng2-spin-kit#5]
In your ng2-spin-kit/app/spinner components, each component uses a hardcoded path such as: `templateUrl: 'app/spinner/pulse/pulse.html'`. This results in a not found for my project and I'm sure for most other projects. It's probably best to use a `template: require('./filename.html')` here

**Comment by mrzepinski** [comment]
@ncfx Try `0.2.0` version ;)

**Comment by jhuntoo** [comment]
@mrzepinski This issue is still occurring. Using templateUrl and styleUrl is probably not the best way to publish components as this causes issues with bundlers like webpack in my case.

**Comment by mrzepinski** [comment]
@jhuntoo I merged your changes. Thanks. Try `0.3.0` version.

**Comment by jhuntoo** [comment]
Thanks @mrzepinski. I forgot to require the css as well! I'll submit another PR!

**Comment by ncfx** [comment]
can someone push the latest to npm? thanks!

**Comment by mrzepinski** [comment]
@ncfx It's done ;)

**Comment by mrzepinski** [comment]
@ncfx Ping ;)
