### ISSUE TITLE
__moduleName is an undeclared identifier

### ISSUE THREAD

**Issue by jhuntoo** [WoltersKluwerPL/ng2-spin-kit#9]
Hi, what is the purpose of __moduleName that is in all the components ?

It's not declared anywhere and also not imported so this causes problems with typescript
`Cannot find name '__moduleName'.`
 I can get around this by defining this identifier in webpack, but i think this should be addressed. Using these measures is something usually reserved for integrating with pure JS libraries like jquery, and not native typescript projects.

By using this "unknown identifier", all folks who use bundlers will have to add extra configuration, and this library won't work out-of-the-box.

**Comment by mrzepinski** [comment]
@jhuntoo __moduleName is for SystemJS. It works for me fine but I don't use Webpack or JSPM. Your solution with require solves that issue. I will remove __moduleName right now.
